# Generated by Django 4.0.3 on 2022-06-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='active',
        ),
    ]
